<Project Sdk="Aspire.AppHost.Sdk/13.3.4">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>2541bdd6-0eb1-49c9-8fce-c1cc51186073</UserSecretsId>
  </PropertyGroup>

</Project>
