// <auto-generated />
// This file is used to suppress code analysis warnings in EF Core migration files.
// Migration files are generated code and should not be modified.

using System.Diagnostics.CodeAnalysis;

// Exclude all migrations from code coverage
[assembly: ExcludeFromCodeCoverage]

[assembly: SuppressMessage(
    "Performance",
    "CA1861:Avoid constant arrays as arguments",
    Justification = "Generated migration code - should not be modified",
    Scope = "namespaceanddescendants",
    Target = "~N:OpenIdentityStack.Infrastructure.Persistence.Migrations")]
