namespace OpenIdentityStack.Domain.Applications;

public static class ApplicationTypePolicyCatalog
{
    private static readonly Dictionary<ApplicationType, ApplicationTypePolicy> policies = new()
    {
        [ApplicationType.Web] = new(
            ApplicationType.Web,
            IsSelectable: true,
            UnavailabilityReason: null,
            DefaultClientProfile: ClientProfile.Confidential,
            AllowedClientProfiles: CreateProfiles(ClientProfile.Confidential),
            AllowedGrantTypes: CreateGrants("authorization_code", "refresh_token"),
            DefaultGrantTypes: CreateGrants("authorization_code"),
            Options: CreateOptions(
                (ApplicationOptionKey.ApplicationType, ApplicationOptionAvailability.ReadOnly),
                (ApplicationOptionKey.ClientProfile, ApplicationOptionAvailability.ReadOnly),
                (ApplicationOptionKey.TokenEndpointAuthenticationMethod, ApplicationOptionAvailability.Available),
                (ApplicationOptionKey.ClientSecrets, ApplicationOptionAvailability.Available),
                (ApplicationOptionKey.MultipleActiveSecrets, ApplicationOptionAvailability.Available),
                (ApplicationOptionKey.SecretRotationAndRevocation, ApplicationOptionAvailability.Available),
                (ApplicationOptionKey.ClientCertificates, ApplicationOptionAvailability.Advanced),
                (ApplicationOptionKey.Jwks, ApplicationOptionAvailability.Advanced),
                (ApplicationOptionKey.AllowedScopes, ApplicationOptionAvailability.Available),
                (ApplicationOptionKey.AllowedAudiences, ApplicationOptionAvailability.Available),
                (ApplicationOptionKey.AuthorizationCodeGrant, ApplicationOptionAvailability.Available),
                (ApplicationOptionKey.DeviceCodeGrant, ApplicationOptionAvailability.Hidden),
                (ApplicationOptionKey.ClientCredentialsGrant, ApplicationOptionAvailability.Hidden),
                (ApplicationOptionKey.RefreshTokenGrant, ApplicationOptionAvailability.Available),
                (ApplicationOptionKey.RedirectUris, ApplicationOptionAvailability.Available),
                (ApplicationOptionKey.PostLogoutRedirectUris, ApplicationOptionAvailability.Available),
                (ApplicationOptionKey.AllowedWebOrigins, ApplicationOptionAvailability.Advanced),
                (ApplicationOptionKey.Pkce, ApplicationOptionAvailability.Available),
                (ApplicationOptionKey.Consent, ApplicationOptionAvailability.Available),
                (ApplicationOptionKey.LoginInitiationUri, ApplicationOptionAvailability.Advanced),
                (ApplicationOptionKey.FrontChannelLogout, ApplicationOptionAvailability.Advanced),
                (ApplicationOptionKey.BackChannelLogout, ApplicationOptionAvailability.Advanced),
                (ApplicationOptionKey.TokenLifetimeOverrides, ApplicationOptionAvailability.Advanced),
                (ApplicationOptionKey.SenderConstrainedAccessTokens, ApplicationOptionAvailability.Advanced)),
            RequirePkce: false,
            DefaultRequirePkce: true,
            DefaultRequireConsent: true,
            RequiresRedirectUris: true),
        [ApplicationType.SinglePage] = new(
            ApplicationType.SinglePage,
            IsSelectable: true,
            UnavailabilityReason: null,
            DefaultClientProfile: ClientProfile.Public,
            AllowedClientProfiles: CreateProfiles(ClientProfile.Public),
            AllowedGrantTypes: CreateGrants("authorization_code", "refresh_token"),
            DefaultGrantTypes: CreateGrants("authorization_code"),
            Options: CreateOptions(
                (ApplicationOptionKey.ApplicationType, ApplicationOptionAvailability.ReadOnly),
                (ApplicationOptionKey.ClientProfile, ApplicationOptionAvailability.ReadOnly),
                (ApplicationOptionKey.TokenEndpointAuthenticationMethod, ApplicationOptionAvailability.ReadOnly),
                (ApplicationOptionKey.ClientSecrets, ApplicationOptionAvailability.Hidden),
                (ApplicationOptionKey.MultipleActiveSecrets, ApplicationOptionAvailability.Hidden),
                (ApplicationOptionKey.SecretRotationAndRevocation, ApplicationOptionAvailability.Hidden),
                (ApplicationOptionKey.ClientCertificates, ApplicationOptionAvailability.Hidden),
                (ApplicationOptionKey.Jwks, ApplicationOptionAvailability.Hidden),
                (ApplicationOptionKey.AllowedScopes, ApplicationOptionAvailability.Available),
                (ApplicationOptionKey.AllowedAudiences, ApplicationOptionAvailability.Available),
                (ApplicationOptionKey.AuthorizationCodeGrant, ApplicationOptionAvailability.Available),
                (ApplicationOptionKey.DeviceCodeGrant, ApplicationOptionAvailability.Hidden),
                (ApplicationOptionKey.ClientCredentialsGrant, ApplicationOptionAvailability.Hidden),
                (ApplicationOptionKey.RefreshTokenGrant, ApplicationOptionAvailability.Available),
                (ApplicationOptionKey.RedirectUris, ApplicationOptionAvailability.Available),
                (ApplicationOptionKey.PostLogoutRedirectUris, ApplicationOptionAvailability.Available),
                (ApplicationOptionKey.AllowedWebOrigins, ApplicationOptionAvailability.Available),
                (ApplicationOptionKey.Pkce, ApplicationOptionAvailability.ReadOnly),
                (ApplicationOptionKey.Consent, ApplicationOptionAvailability.Available),
                (ApplicationOptionKey.TokenLifetimeOverrides, ApplicationOptionAvailability.Advanced),
                (ApplicationOptionKey.SenderConstrainedAccessTokens, ApplicationOptionAvailability.Advanced)),
            RequirePkce: true,
            DefaultRequirePkce: true,
            DefaultRequireConsent: true,
            RequiresRedirectUris: true),
        [ApplicationType.Native] = new(
            ApplicationType.Native,
            IsSelectable: true,
            UnavailabilityReason: null,
            DefaultClientProfile: ClientProfile.Public,
            AllowedClientProfiles: CreateProfiles(ClientProfile.Public),
            AllowedGrantTypes: CreateGrants("authorization_code", "refresh_token"),
            DefaultGrantTypes: CreateGrants("authorization_code"),
            Options: CreateOptions(
                (ApplicationOptionKey.ApplicationType, ApplicationOptionAvailability.ReadOnly),
                (ApplicationOptionKey.ClientProfile, ApplicationOptionAvailability.ReadOnly),
                (ApplicationOptionKey.TokenEndpointAuthenticationMethod, ApplicationOptionAvailability.ReadOnly),
                (ApplicationOptionKey.ClientSecrets, ApplicationOptionAvailability.Hidden),
                (ApplicationOptionKey.MultipleActiveSecrets, ApplicationOptionAvailability.Hidden),
                (ApplicationOptionKey.SecretRotationAndRevocation, ApplicationOptionAvailability.Hidden),
                (ApplicationOptionKey.ClientCertificates, ApplicationOptionAvailability.Hidden),
                (ApplicationOptionKey.Jwks, ApplicationOptionAvailability.Advanced),
                (ApplicationOptionKey.AllowedScopes, ApplicationOptionAvailability.Available),
                (ApplicationOptionKey.AllowedAudiences, ApplicationOptionAvailability.Available),
                (ApplicationOptionKey.AuthorizationCodeGrant, ApplicationOptionAvailability.Available),
                (ApplicationOptionKey.DeviceCodeGrant, ApplicationOptionAvailability.Hidden),
                (ApplicationOptionKey.ClientCredentialsGrant, ApplicationOptionAvailability.Hidden),
                (ApplicationOptionKey.RefreshTokenGrant, ApplicationOptionAvailability.Available),
                (ApplicationOptionKey.RedirectUris, ApplicationOptionAvailability.Available),
                (ApplicationOptionKey.NativeRedirectUriPatterns, ApplicationOptionAvailability.Available),
                (ApplicationOptionKey.LoopbackRedirectUri, ApplicationOptionAvailability.Available),
                (ApplicationOptionKey.PostLogoutRedirectUris, ApplicationOptionAvailability.Available),
                (ApplicationOptionKey.Pkce, ApplicationOptionAvailability.ReadOnly),
                (ApplicationOptionKey.Consent, ApplicationOptionAvailability.Available),
                (ApplicationOptionKey.TokenLifetimeOverrides, ApplicationOptionAvailability.Advanced),
                (ApplicationOptionKey.SenderConstrainedAccessTokens, ApplicationOptionAvailability.Advanced)),
            RequirePkce: true,
            DefaultRequirePkce: true,
            DefaultRequireConsent: true,
            RequiresRedirectUris: true),
        [ApplicationType.MachineToMachine] = new(
            ApplicationType.MachineToMachine,
            IsSelectable: true,
            UnavailabilityReason: null,
            DefaultClientProfile: ClientProfile.Confidential,
            AllowedClientProfiles: CreateProfiles(ClientProfile.Confidential),
            AllowedGrantTypes: CreateGrants("client_credentials"),
            DefaultGrantTypes: CreateGrants("client_credentials"),
            Options: CreateOptions(
                (ApplicationOptionKey.ApplicationType, ApplicationOptionAvailability.ReadOnly),
                (ApplicationOptionKey.ClientProfile, ApplicationOptionAvailability.ReadOnly),
                (ApplicationOptionKey.TokenEndpointAuthenticationMethod, ApplicationOptionAvailability.Available),
                (ApplicationOptionKey.ClientSecrets, ApplicationOptionAvailability.Available),
                (ApplicationOptionKey.MultipleActiveSecrets, ApplicationOptionAvailability.Available),
                (ApplicationOptionKey.SecretRotationAndRevocation, ApplicationOptionAvailability.Available),
                (ApplicationOptionKey.ClientCertificates, ApplicationOptionAvailability.Advanced),
                (ApplicationOptionKey.Jwks, ApplicationOptionAvailability.Advanced),
                (ApplicationOptionKey.AllowedScopes, ApplicationOptionAvailability.Available),
                (ApplicationOptionKey.AllowedAudiences, ApplicationOptionAvailability.Available),
                (ApplicationOptionKey.AuthorizationCodeGrant, ApplicationOptionAvailability.Hidden),
                (ApplicationOptionKey.DeviceCodeGrant, ApplicationOptionAvailability.Hidden),
                (ApplicationOptionKey.ClientCredentialsGrant, ApplicationOptionAvailability.Available),
                (ApplicationOptionKey.RefreshTokenGrant, ApplicationOptionAvailability.Hidden),
                (ApplicationOptionKey.RedirectUris, ApplicationOptionAvailability.Hidden),
                (ApplicationOptionKey.PostLogoutRedirectUris, ApplicationOptionAvailability.Hidden),
                (ApplicationOptionKey.Pkce, ApplicationOptionAvailability.Hidden),
                (ApplicationOptionKey.Consent, ApplicationOptionAvailability.Hidden),
                (ApplicationOptionKey.TokenLifetimeOverrides, ApplicationOptionAvailability.Advanced),
                (ApplicationOptionKey.SenderConstrainedAccessTokens, ApplicationOptionAvailability.Advanced)),
            RequirePkce: false,
            DefaultRequirePkce: false,
            DefaultRequireConsent: false,
            RequiresRedirectUris: false),
        [ApplicationType.Device] = new(
            ApplicationType.Device,
            IsSelectable: false,
            UnavailabilityReason: "Device applications remain reserved until device authorization flow support is implemented and verified.",
            DefaultClientProfile: ClientProfile.Public,
            AllowedClientProfiles: CreateProfiles(ClientProfile.Public),
            AllowedGrantTypes: CreateGrants("urn:ietf:params:oauth:grant-type:device_code", "refresh_token"),
            DefaultGrantTypes: CreateGrants("urn:ietf:params:oauth:grant-type:device_code"),
            Options: CreateOptions(
                (ApplicationOptionKey.ApplicationType, ApplicationOptionAvailability.ReadOnly),
                (ApplicationOptionKey.ClientProfile, ApplicationOptionAvailability.ReadOnly),
                (ApplicationOptionKey.TokenEndpointAuthenticationMethod, ApplicationOptionAvailability.ReadOnly),
                (ApplicationOptionKey.ClientSecrets, ApplicationOptionAvailability.Hidden),
                (ApplicationOptionKey.MultipleActiveSecrets, ApplicationOptionAvailability.Hidden),
                (ApplicationOptionKey.SecretRotationAndRevocation, ApplicationOptionAvailability.Hidden),
                (ApplicationOptionKey.ClientCertificates, ApplicationOptionAvailability.Advanced),
                (ApplicationOptionKey.Jwks, ApplicationOptionAvailability.Advanced),
                (ApplicationOptionKey.AllowedScopes, ApplicationOptionAvailability.Available),
                (ApplicationOptionKey.AllowedAudiences, ApplicationOptionAvailability.Available),
                (ApplicationOptionKey.AuthorizationCodeGrant, ApplicationOptionAvailability.Hidden),
                (ApplicationOptionKey.DeviceCodeGrant, ApplicationOptionAvailability.ReadOnly),
                (ApplicationOptionKey.ClientCredentialsGrant, ApplicationOptionAvailability.Hidden),
                (ApplicationOptionKey.RefreshTokenGrant, ApplicationOptionAvailability.Available),
                (ApplicationOptionKey.RedirectUris, ApplicationOptionAvailability.Hidden),
                (ApplicationOptionKey.PostLogoutRedirectUris, ApplicationOptionAvailability.Hidden),
                (ApplicationOptionKey.Pkce, ApplicationOptionAvailability.Hidden),
                (ApplicationOptionKey.Consent, ApplicationOptionAvailability.Available),
                (ApplicationOptionKey.DeviceUserCodeSettings, ApplicationOptionAvailability.Available),
                (ApplicationOptionKey.DevicePollingAndExpiry, ApplicationOptionAvailability.Available),
                (ApplicationOptionKey.TokenLifetimeOverrides, ApplicationOptionAvailability.Advanced),
                (ApplicationOptionKey.SenderConstrainedAccessTokens, ApplicationOptionAvailability.Advanced)),
            RequirePkce: false,
            DefaultRequirePkce: false,
            DefaultRequireConsent: true,
            RequiresRedirectUris: false),
        [ApplicationType.Custom] = new(
            ApplicationType.Custom,
            IsSelectable: false,
            UnavailabilityReason: "Custom applications are reserved for legacy migration review.",
            DefaultClientProfile: ClientProfile.Public,
            AllowedClientProfiles: CreateProfiles(ClientProfile.Public, ClientProfile.Confidential),
            AllowedGrantTypes: CreateGrants(
                "authorization_code",
                "client_credentials",
                "refresh_token",
                "urn:ietf:params:oauth:grant-type:device_code"),
            DefaultGrantTypes: CreateGrants(),
            Options: CreateOptions(
                (ApplicationOptionKey.ApplicationType, ApplicationOptionAvailability.ReadOnly),
                (ApplicationOptionKey.ClientProfile, ApplicationOptionAvailability.Available),
                (ApplicationOptionKey.TokenEndpointAuthenticationMethod, ApplicationOptionAvailability.Advanced),
                (ApplicationOptionKey.ClientSecrets, ApplicationOptionAvailability.Available),
                (ApplicationOptionKey.MultipleActiveSecrets, ApplicationOptionAvailability.Available),
                (ApplicationOptionKey.SecretRotationAndRevocation, ApplicationOptionAvailability.Available),
                (ApplicationOptionKey.ClientCertificates, ApplicationOptionAvailability.Advanced),
                (ApplicationOptionKey.Jwks, ApplicationOptionAvailability.Advanced),
                (ApplicationOptionKey.AllowedScopes, ApplicationOptionAvailability.Available),
                (ApplicationOptionKey.AllowedAudiences, ApplicationOptionAvailability.Available),
                (ApplicationOptionKey.AuthorizationCodeGrant, ApplicationOptionAvailability.Available),
                (ApplicationOptionKey.DeviceCodeGrant, ApplicationOptionAvailability.Available),
                (ApplicationOptionKey.ClientCredentialsGrant, ApplicationOptionAvailability.Available),
                (ApplicationOptionKey.RefreshTokenGrant, ApplicationOptionAvailability.Available),
                (ApplicationOptionKey.RedirectUris, ApplicationOptionAvailability.Available),
                (ApplicationOptionKey.PostLogoutRedirectUris, ApplicationOptionAvailability.Available),
                (ApplicationOptionKey.Pkce, ApplicationOptionAvailability.Available),
                (ApplicationOptionKey.Consent, ApplicationOptionAvailability.Available),
                (ApplicationOptionKey.TokenLifetimeOverrides, ApplicationOptionAvailability.Advanced),
                (ApplicationOptionKey.SenderConstrainedAccessTokens, ApplicationOptionAvailability.Advanced)),
            RequirePkce: false,
            DefaultRequirePkce: false,
            DefaultRequireConsent: true,
            RequiresRedirectUris: false)
    };

    public static ApplicationTypePolicy GetPolicy(ApplicationType type) => policies[type];

    private static HashSet<ClientProfile> CreateProfiles(params ClientProfile[] profiles) =>
        new HashSet<ClientProfile>(profiles);

    private static HashSet<string> CreateGrants(params string[] grantTypes) =>
        new HashSet<string>(grantTypes, StringComparer.OrdinalIgnoreCase);

    private static Dictionary<ApplicationOptionKey, ApplicationOptionAvailability> CreateOptions(
        params (ApplicationOptionKey Key, ApplicationOptionAvailability Availability)[] values) =>
        values.ToDictionary(value => value.Key, value => value.Availability);
}
